// vehicles.js - vehicle definitions and helpers

export const vehicles = [
  // ── CARS ──────────────────────────────────────────────────────────────────
  {
    id: "rusty_hatchback",
    name: "Rusty Hatchback",
    type: "car",
    stats: { speed: 5, acceleration: 5, fuelEfficiency: 5, grip: 5, traction: 5, torque: 0.015, fuelCapacity: 100 },
    cost: 0, defaultUnlocked: true,
    bodyWidth: 90, bodyHeight: 32, wheelBase: 70, wheelRadius: 16, wheelYOffset: 20, suspensionLength: 10,
    physics: { density: 0.0018 },
    palette: { body: "#f0c27b", accent: "#4b1248" },
  },
  {
    id: "monster_truck",
    name: "Monster Truck",
    type: "car",
    stats: { speed: 3, acceleration: 4, fuelEfficiency: 4, grip: 9, traction: 9, torque: 0.02, fuelCapacity: 110 },
    cost: 500, defaultUnlocked: true,
    bodyWidth: 110, bodyHeight: 38, wheelBase: 80, wheelRadius: 22, wheelYOffset: 26, suspensionLength: 16,
    physics: { density: 0.0025 },
    palette: { body: "#3a7bd5", accent: "#0f2027" },
  },
  {
    id: "rally_racer",
    name: "Rally Racer",
    type: "car",
    stats: { speed: 8, acceleration: 7, fuelEfficiency: 4, grip: 4, traction: 4, torque: 0.018, fuelCapacity: 95 },
    cost: 900, defaultUnlocked: false,
    bodyWidth: 92, bodyHeight: 30, wheelBase: 72, wheelRadius: 16, wheelYOffset: 18, suspensionLength: 10,
    physics: { density: 0.0021 },
    palette: { body: "#ff512f", accent: "#dd2476" },
  },
  {
    id: "muscle_car",
    name: "Muscle Car",
    type: "car",
    stats: { speed: 9, acceleration: 7, fuelEfficiency: 3, grip: 5, traction: 5, torque: 0.022, fuelCapacity: 85 },
    cost: 1100, defaultUnlocked: false,
    bodyWidth: 100, bodyHeight: 32, wheelBase: 78, wheelRadius: 17, wheelYOffset: 20, suspensionLength: 10,
    physics: { density: 0.0022 },
    palette: { body: "#f7971e", accent: "#ffd200" },
  },
  {
    id: "jeep_4x4",
    name: "Jeep 4x4",
    type: "car",
    stats: { speed: 5, acceleration: 5, fuelEfficiency: 5, grip: 8, traction: 8, torque: 0.017, fuelCapacity: 100 },
    cost: 1000, defaultUnlocked: false,
    bodyWidth: 88, bodyHeight: 36, wheelBase: 70, wheelRadius: 18, wheelYOffset: 22, suspensionLength: 14,
    physics: { density: 0.0024 },
    palette: { body: "#11998e", accent: "#38ef7d" },
  },
  {
    id: "sports_coupe",
    name: "Sports Coupe",
    type: "car",
    stats: { speed: 10, acceleration: 8, fuelEfficiency: 3, grip: 5, traction: 4, torque: 0.02, fuelCapacity: 80 },
    cost: 1300, defaultUnlocked: false,
    bodyWidth: 92, bodyHeight: 28, wheelBase: 74, wheelRadius: 16, wheelYOffset: 18, suspensionLength: 9,
    physics: { density: 0.002 },
    palette: { body: "#00c6ff", accent: "#0072ff" },
  },
  {
    id: "dune_buggy",
    name: "Dune Buggy",
    type: "car",
    stats: { speed: 7, acceleration: 9, fuelEfficiency: 6, grip: 7, traction: 7, torque: 0.018, fuelCapacity: 95 },
    cost: 1200, defaultUnlocked: false,
    bodyWidth: 82, bodyHeight: 28, wheelBase: 68, wheelRadius: 16, wheelYOffset: 20, suspensionLength: 14,
    physics: { density: 0.0017 },
    palette: { body: "#ffe259", accent: "#ffa751" },
  },
  {
    id: "tank",
    name: "Tank",
    type: "car",
    stats: { speed: 3, acceleration: 3, fuelEfficiency: 2, grip: 10, traction: 10, torque: 0.03, fuelCapacity: 120 },
    cost: 2000, defaultUnlocked: false,
    bodyWidth: 130, bodyHeight: 40, wheelBase: 90, wheelRadius: 20, wheelYOffset: 24, suspensionLength: 12,
    physics: { density: 0.004 },
    palette: { body: "#536976", accent: "#292e49" },
  },
  {
    id: "pickup_truck",
    name: "Pickup Truck",
    type: "car",
    stats: { speed: 6, acceleration: 6, fuelEfficiency: 5, grip: 7, traction: 7, torque: 0.018, fuelCapacity: 105 },
    cost: 1000, defaultUnlocked: false,
    bodyWidth: 100, bodyHeight: 34, wheelBase: 80, wheelRadius: 18, wheelYOffset: 22, suspensionLength: 12,
    physics: { density: 0.0025 },
    palette: { body: "#f5515f", accent: "#9f041b" },
  },
  {
    id: "electric_car",
    name: "Electric Car",
    type: "car",
    stats: { speed: 8, acceleration: 8, fuelEfficiency: 10, grip: 6, traction: 6, torque: 0.019, fuelCapacity: 130 },
    cost: 1500, defaultUnlocked: false,
    bodyWidth: 92, bodyHeight: 30, wheelBase: 72, wheelRadius: 16, wheelYOffset: 18, suspensionLength: 10,
    physics: { density: 0.0021 },
    palette: { body: "#36d1dc", accent: "#5b86e5" },
  },

  // ── BIKES ────────────────────────────────────────────────────────────────
  {
    id: "dirt_bike",
    name: "Dirt Bike",
    type: "bike",
    stats: { speed: 7, acceleration: 8, fuelEfficiency: 7, grip: 7, traction: 6, torque: 0.017, fuelCapacity: 90 },
    cost: 0, defaultUnlocked: true,
    bodyWidth: 60, bodyHeight: 24, wheelBase: 60, wheelRadius: 14, wheelYOffset: 20, suspensionLength: 10,
    physics: { density: 0.0014 },
    palette: { body: "#ff9966", accent: "#ff5e62" },
  },
  {
    id: "chopper",
    name: "Chopper",
    type: "bike",
    stats: { speed: 5, acceleration: 4, fuelEfficiency: 5, grip: 6, traction: 6, torque: 0.015, fuelCapacity: 95 },
    cost: 700, defaultUnlocked: false,
    bodyWidth: 70, bodyHeight: 24, wheelBase: 70, wheelRadius: 15, wheelYOffset: 20, suspensionLength: 10,
    physics: { density: 0.0018 },
    palette: { body: "#c31432", accent: "#240b36" },
  },
  {
    id: "sport_bike",
    name: "Sport Bike",
    type: "bike",
    stats: { speed: 10, acceleration: 10, fuelEfficiency: 5, grip: 7, traction: 6, torque: 0.021, fuelCapacity: 85 },
    cost: 1600, defaultUnlocked: false,
    bodyWidth: 64, bodyHeight: 24, wheelBase: 64, wheelRadius: 14, wheelYOffset: 20, suspensionLength: 9,
    physics: { density: 0.0017 },
    palette: { body: "#1a2980", accent: "#26d0ce" },
  },
  {
    id: "scrambler",
    name: "Scrambler",
    type: "bike",
    stats: { speed: 7, acceleration: 7, fuelEfficiency: 7, grip: 7, traction: 7, torque: 0.017, fuelCapacity: 95 },
    cost: 900, defaultUnlocked: false,
    bodyWidth: 60, bodyHeight: 24, wheelBase: 62, wheelRadius: 14, wheelYOffset: 20, suspensionLength: 10,
    physics: { density: 0.0016 },
    palette: { body: "#00b09b", accent: "#96c93d" },
  },
  {
    id: "mini_moto",
    name: "Mini Moto",
    type: "bike",
    stats: { speed: 6, acceleration: 8, fuelEfficiency: 8, grip: 6, traction: 6, torque: 0.015, fuelCapacity: 80 },
    cost: 600, defaultUnlocked: false,
    bodyWidth: 52, bodyHeight: 22, wheelBase: 52, wheelRadius: 13, wheelYOffset: 18, suspensionLength: 9,
    physics: { density: 0.0013 },
    palette: { body: "#4e54c8", accent: "#8f94fb" },
  },
  {
    id: "enduro_bike",
    name: "Enduro Bike",
    type: "bike",
    stats: { speed: 7, acceleration: 7, fuelEfficiency: 9, grip: 7, traction: 7, torque: 0.017, fuelCapacity: 105 },
    cost: 1100, defaultUnlocked: false,
    bodyWidth: 60, bodyHeight: 24, wheelBase: 62, wheelRadius: 14, wheelYOffset: 20, suspensionLength: 11,
    physics: { density: 0.0016 },
    palette: { body: "#ffafbd", accent: "#ffc3a0" },
  },
  {
    id: "cafe_racer",
    name: "Cafe Racer",
    type: "bike",
    stats: { speed: 8, acceleration: 7, fuelEfficiency: 6, grip: 8, traction: 7, torque: 0.018, fuelCapacity: 90 },
    cost: 1000, defaultUnlocked: false,
    bodyWidth: 64, bodyHeight: 24, wheelBase: 64, wheelRadius: 14, wheelYOffset: 20, suspensionLength: 9,
    physics: { density: 0.0017 },
    palette: { body: "#ffe000", accent: "#799f0c" },
  },
  {
    id: "bmx",
    name: "BMX",
    type: "bike",
    stats: { speed: 5, acceleration: 8, fuelEfficiency: 10, grip: 6, traction: 5, torque: 0.012, fuelCapacity: 75 },
    cost: 500, defaultUnlocked: false,
    bodyWidth: 50, bodyHeight: 22, wheelBase: 50, wheelRadius: 13, wheelYOffset: 18, suspensionLength: 9,
    physics: { density: 0.0011 },
    palette: { body: "#ff9a9e", accent: "#fad0c4" },
  },
  {
    id: "cruiser_bike",
    name: "Cruiser",
    type: "bike",
    stats: { speed: 6, acceleration: 5, fuelEfficiency: 6, grip: 8, traction: 8, torque: 0.015, fuelCapacity: 95 },
    cost: 950, defaultUnlocked: false,
    bodyWidth: 68, bodyHeight: 24, wheelBase: 70, wheelRadius: 15, wheelYOffset: 20, suspensionLength: 10,
    physics: { density: 0.0018 },
    palette: { body: "#fffea5", accent: "#ffe259" },
  },
  {
    id: "supermoto",
    name: "Supermoto",
    type: "bike",
    stats: { speed: 8, acceleration: 8, fuelEfficiency: 7, grip: 8, traction: 7, torque: 0.019, fuelCapacity: 95 },
    cost: 1300, defaultUnlocked: false,
    bodyWidth: 60, bodyHeight: 24, wheelBase: 62, wheelRadius: 14, wheelYOffset: 20, suspensionLength: 10,
    physics: { density: 0.0017 },
    palette: { body: "#fdfbfb", accent: "#ebedee" },
  },
];

export function getDefaultVehicleId() {
  return "rusty_hatchback";
}
